#////////////////////////////////////////////////////////////////////////////////
#//  Copyright (c) 2020-2021 Prashant K. Jha, Tobias Koeppl, Andreas Wagner
#//
#//  Distributed under the Boost Software License, Version 1.0. (See accompanying
#//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#////////////////////////////////////////////////////////////////////////////////

version: 2.1
parameters:
  docker-img-os:
    type: string
    default: u1804
    
commands:
  libcmake:
    parameters:
      cmake-args:
        type: string
        default: -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DEnable_Tests=ON -DLIBMESH_DIR=/usr/lib/libmesh-1.5.0 -DPETSC_LIB=/usr/lib/petsc-3.13.3
    steps:
      - run: 
          name: Configure
          command: |
            mkdir -p build 
            cd build 
            cmake <<parameters.cmake-args>> ..
  libmake:
    steps:
      - run: 
          name: Build
          command: |
            cd build 
            make -j 2
  libtest:
    parameters:
      verb-flag:
        type: string
        default: --verbose
    steps:
      - run: 
          name: Test
          command: |
            cd build 
            ctest <<parameters.verb-flag>>
  libdoc:
    steps:
      - run: 
          name: Documentation
          command: |
            cd build 
            make doc        

jobs:
    build:
        docker:
          - image: prashjha/<<pipeline.parameters.docker-img-os>>-comp:latest
        steps:
            - checkout
            - libcmake
            - libmake
    deploy:
      machine:
        image: ubuntu-2004:202008-01
      environment:
        IMAGE_FILE_NAME: .circleci/Docker/Dockerfile-<<pipeline.parameters.docker-img-os>>
        IMAGE_NAME: <<pipeline.parameters.docker-img-os>>-tumormodels:latest
      steps:
        - checkout
        - run:
            name: Build docker
            command: |
              docker build -t prashjha/${IMAGE_NAME} -f ${IMAGE_FILE_NAME} .
              docker images
        - run:
            name: Deploy to docker hub
            command: |
              if [ "${CIRCLE_BRANCH}" == "main" ]; then
                 docker login -u $DOCKER_USER -p $DOCKER_PASS
                 docker push prashjha/${IMAGE_NAME}
              fi
        - run:
            name: Deploy to github
            command: |
              if [ "${CIRCLE_BRANCH}" == "main" ]; then
                 docker login docker.pkg.github.com --username prashjha -p ${G_TOKEN}
                 docker tag prashjha/${IMAGE_NAME} docker.pkg.github.com/prashjha/tumormodels/${IMAGE_NAME}
                 docker push docker.pkg.github.com/prashjha/tumormodels/${IMAGE_NAME}
              fi
workflows:
  version: 2
  build_code:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          filters:
            branches:
              ignore: gh-pages
          requires:
            - build
