# base ubuntu image with petsc, libmesh, hpx
FROM prashjha/u1804-comp:latest

## build command
## docker build --network=host --no-cache  -t tumormodels-u1804 -f Dockerfile-u1804 .

# Set metadata
LABEL maintainer="Prashant K. Jha <pjha.sci@gmail.com>"
LABEL description="Ubuntu 18.04 with TumorModels library installed"

WORKDIR /

RUN git clone  https://github.com/prashjha/TumorModels.git

RUN cd /TumorModels && \
		mkdir build && \
		cd build && \
		cmake -DLIBMESH_DIR=${LIBMESH_DIR} \
					-DPETSC_LIB=${PETSC_DIR}/lib \
					-DCMAKE_C_COMPILER=/usr/bin/gcc \
					-DCMAKE_CXX_COMPILER=/usr/bin/g++ \
					-DCMAKE_BUILD_TYPE=Release \
					-DEnable_Tests=ON \
					.. && \
		make -j 2 && \
		make install

